// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0WKDaNF_5Rgrpqrkp3bDbCLxq5n7U3M',
    appId: '1:824763935188:web:a687b427847f61406b4e41',
    messagingSenderId: '824763935188',
    projectId: 'food-delivery-258e0',
    authDomain: 'food-delivery-258e0.firebaseapp.com',
    storageBucket: 'food-delivery-258e0.appspot.com',
    measurementId: 'G-J43ZBX4GLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6axrLIcin3fys9il3Wc4v10afpErKnXI',
    appId: '1:824763935188:android:98e9cea997a507106b4e41',
    messagingSenderId: '824763935188',
    projectId: 'food-delivery-258e0',
    storageBucket: 'food-delivery-258e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPCCAHDKo9nEUDQQZbKAJ_WiYRrXbNH4',
    appId: '1:824763935188:ios:f4f850b31e736e926b4e41',
    messagingSenderId: '824763935188',
    projectId: 'food-delivery-258e0',
    storageBucket: 'food-delivery-258e0.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPCCAHDKo9nEUDQQZbKAJ_WiYRrXbNH4',
    appId: '1:824763935188:ios:f4f850b31e736e926b4e41',
    messagingSenderId: '824763935188',
    projectId: 'food-delivery-258e0',
    storageBucket: 'food-delivery-258e0.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0WKDaNF_5Rgrpqrkp3bDbCLxq5n7U3M',
    appId: '1:824763935188:web:d91cb49f1db657896b4e41',
    messagingSenderId: '824763935188',
    projectId: 'food-delivery-258e0',
    authDomain: 'food-delivery-258e0.firebaseapp.com',
    storageBucket: 'food-delivery-258e0.appspot.com',
    measurementId: 'G-RBW2SZSSQN',
  );

}